onlyBuiltDependencies:
  - sharp

overrides:
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  next@>=15.6.0-canary.0 <16.1.5: '>=16.1.5'
  next@>=16.0.0-beta.0 <16.1.5: '>=16.1.5'
  next@>=16.1.0-canary.0 <16.1.5: '>=16.1.5'
  qs@<6.14.1: '>=6.14.1'
  tar@<7.5.7: '>=7.5.7'
  tar@<=7.5.2: '>=7.5.3'
  tar@<=7.5.3: '>=7.5.4'
